import { Question, QuestionType } from './types';

export const TOTAL_QUIZ_TIME = 30 * 60; // 30 Minuten in Sekunden

export const QUIZ_QUESTIONS: Question[] = [
  {
    id: 'q1',
    text: 'Was ist eine mögliche Konsequenz von AI Jailbreaks?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q1o1', text: 'Die Generierung unzensierter Inhalte durch KI-Chatbots.' },
      { id: 'q1o2', text: 'Die Verringerung der Notwendigkeit menschlicher Eingriffe in KI-Entscheidungen.' },
      { id: 'q1o3', text: 'Die Beschleunigung der globalen KI-Entwicklung.' },
      { id: 'q1o4', text: 'Die Erhöhung der Sicherheit und Zuverlässigkeit von KI-Systemen.' },
    ],
    correctAnswers: ['q1o1'],
  },
  {
    id: 'q2',
    text: 'Welche Anforderungen stellt die DSGVO an die Verarbeitung personenbezogener Daten im Kontext von KI?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q2o1', text: 'Daten müssen für festgelegte, eindeutige und legitime Zwecke erhoben werden.' },
      { id: 'q2o2', text: 'Die DSGVO erlaubt die unbegrenzte Weiterverarbeitung personenbezogener Daten.' },
      { id: 'q2o3', text: 'Personenbezogene Daten müssen ohne Einwilligung der betroffenen Person verarbeitet werden.' },
      { id: 'q2o4', text: 'Eine wirksame Einwilligung muss nicht spezifisch und informiert sein.' },
    ],
    correctAnswers: ['q2o1'],
  },
  {
    id: 'q3',
    text: 'Wie sollte eine strukturierte Aufgabenstellung idealerweise enden, um die Effektivität zu maximieren?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q3o1', text: 'Mit einer detaillierten Beschreibung der Rolle.' },
      { id: 'q3o2', text: 'Mit einem Beispiel für eine Lösung.' },
      { id: 'q3o3', text: 'Mit der Angabe des Kontextes.' },
      { id: 'q3o4', text: 'Mit der eigentlichen Aufgabenstellung.' },
    ],
    correctAnswers: ['q3o4'],
  },
  {
    id: 'q4',
    text: 'Was ist ein Token in Bezug auf Large Language Models (LLMs)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q4o1', text: 'Ein Token ist eine kleinste Einheit der Textverarbeitung in LLMs.' },
      { id: 'q4o2', text: 'Ein Token repräsentiert immer ein ganzes Wort.' },
      { id: 'q4o3', text: 'Ein Token kann ein kurzes Wort, ein Wortteil oder ein Satzzeichen sein.' },
      { id: 'q4o4', text: 'Ein Token ist ein spezielles Symbol, das nur in Programmiersprachen verwendet wird.' },
    ],
    correctAnswers: ['q4o1', 'q4o3'],
  },
  {
    id: 'q5',
    text: 'Welche spezielle Funktion erfüllen regulatorische Sandkästen im Rahmen des EU AI Acts?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q5o1', text: 'Sie ermöglichen es Unternehmen, KI-Innovationen unter Aufsicht zu testen und zu entwickeln.' },
      { id: 'q5o2', text: 'Sie fungieren als Online-Plattformen für den Verkauf von KI-Systemen.' },
      { id: 'q5o3', text: 'Sie dienen als physische Testgelände für KI-Roboter.' },
      { id: 'q5o4', text: 'Sie bieten eine sichere Speicherlösung für KI-Daten.' },
    ],
    correctAnswers: ['q5o1'],
  },
  {
    id: 'q6',
    text: 'Was ist die Funktion eines Tokenizers im Kontext von LLMs?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q6o1', text: 'Er übersetzt Text von einer Sprache in eine andere.' },
      { id: 'q6o2', text: 'Er wandelt Text in numerische Werte um.' },
      { id: 'q6o3', text: 'Er zerlegt den Text in kleinere Einheiten für die Verarbeitung.' },
      { id: 'q6o4', text: 'Er erstellt eine Zusammenfassung des gegebenen Textes.' },
    ],
    correctAnswers: ['q6o2', 'q6o3'],
  },
  {
    id: 'q7',
    text: 'Wie funktioniert die "Tree of Thoughts (ToT)" Technik im Prompt Engineering?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q7o1', text: 'Sie verwendet maschinelles Lernen, um Sprachmodelle selbstständig zu programmieren.' },
      { id: 'q7o2', text: 'Sie analysiert die physische Struktur von Computernetzwerken.' },
      { id: 'q7o3', text: 'Sie ermöglicht es der KI, in eine Art "inneren Diskurs" zu gehen, indem sie mehrere Rollen gleichzeitig einnimmt.' },
      { id: 'q7o4', text: 'Sie optimiert die Speicherverwaltung für Sprachmodelle.' },
    ],
    correctAnswers: ['q7o3'],
  },
  {
    id: 'q8',
    text: 'Welche Technologie wird speziell mit AlphaGo in Verbindung gebracht und welche Architektur nutzt es?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q8o1', text: 'Transformer Modelle.' },
      { id: 'q8o2', text: 'Reinforcement Learning (RL).' },
      { id: 'q8o3', text: 'Deep Belief Networks.' },
      { id: 'q8o4', text: 'Mehrschichtige Perzeptronen.' },
    ],
    correctAnswers: ['q8o2'],
  },
  {
    id: 'q9',
    text: 'Welche Herausforderungen stehen LLMs gegenüber?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q9o1', text: 'Sie könnten Ungenauigkeiten oder Verzerrungen aufweisen, basierend auf den Trainingsdaten.' },
      { id: 'q9o2', text: 'Sie sind unfähig, den Kontext einer Konversation zu erfassen.' },
      { id: 'q9o3', text: 'Sie können nur in einer Sprache kommunizieren.' },
      { id: 'q9o4', text: 'Ihre Antworten sind unabhängig von den Trainingsdaten.' },
    ],
    correctAnswers: ['q9o1'],
  },
  {
    id: 'q10',
    text: 'Was sind Beispiele für eine Rechtsgrundlage zur Verarbeitung personenbezogener Daten nach DSGVO?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q10o1', text: 'Erfüllung eines Vertrags.' },
      { id: 'q10o2', text: 'Einwilligung der betroffenen Person.' },
      { id: 'q10o3', text: 'Datennutzung zu nichtkommerziellen Zwecken.' },
      { id: 'q10o4', text: 'Unzureichender Passwortschutz der Daten.' },
    ],
    correctAnswers: ['q10o1', 'q10o2'],
  },
  {
    id: 'q11',
    text: 'Welche Maßnahmen enthält der EU AI Act, um Innovation und Wachstum von KI in Europa zu fördern?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q11o1', text: 'Beschränkungen für die Forschung und Entwicklung neuer KI-Technologien.' },
      { id: 'q11o2', text: 'Einführung einer Steuer auf KI-Systeme.' },
      { id: 'q11o3', text: 'Unterstützung von KMUs durch die Einrichtung von regulatorischen Sandkästen.' },
      { id: 'q11o4', text: 'Verbot der Entwicklung von KI-Systemen außerhalb der EU.' },
    ],
    correctAnswers: ['q11o3'],
  },
  {
    id: 'q12',
    text: 'Wie berücksichtigen KIs die Tokens beim Lesen?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q12o1', text: 'Von links nach rechts.' },
      { id: 'q12o2', text: 'Alle Tokens gleichzeitig.' },
      { id: 'q12o3', text: 'Von rechts nach links.' },
      { id: 'q12o4', text: 'In einer sequenziellen und linearen Weise.' },
    ],
    correctAnswers: ['q12o2'],
  },
  {
    id: 'q13',
    text: 'Welche positiven Auswirkungen hat Künstliche Intelligenz (KI) auf den Arbeitsmarkt?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q13o1', text: 'Vereinfachung von Arbeitsprozessen.' },
      { id: 'q13o2', text: 'Unterstützung menschlicher Arbeit.' },
      { id: 'q13o3', text: 'Schaffung neuer Arbeitsplätze.' },
      { id: 'q13o4', text: 'Verlängerung der täglichen Arbeitszeiten.' },
    ],
    correctAnswers: ['q13o1', 'q13o2', 'q13o3'],
  },
  {
    id: 'q14',
    text: 'Welche Hauptarten von Operationen gibt es für die Nutzung von LLMs?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
        {id: 'q14o1', text: 'Analytische, Berechnende und Interpretative.'},
        {id: 'q14o2', text: 'Reduktive, Transformative und Generative.'},
        {id: 'q14o3', text: 'Administrative, Organisatorische und Evaluative.'},
        {id: 'q14o4', text: 'Legislative, Judikative, Exekutive.'}
    ],
    correctAnswers: ['q14o2'],
  },
  {
    id: 'q15',
    text: 'Was ist "AI Jailbreak"?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q15o1', text: 'Eine Technik zur Beschleunigung der KI-Entwicklung in streng regulierten Branchen.' },
      { id: 'q15o2', text: 'Das Umgehen von Sicherheitsmaßnahmen von KI-Chatbots.' },
      { id: 'q15o3', text: 'Ein Verfahren zur Verbesserung der Sicherheitsprotokolle in KI-Systemen.' },
      { id: 'q15o4', text: 'Ein Programm zur Ausbildung von KI in Gefängnisverwaltungssystemen.' },
    ],
    correctAnswers: ['q15o2'],
  },
  {
    id: 'q16',
    text: 'Welche Rolle spielt die Regulierung bei der KI-Entwicklung?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q16o1', text: 'Förderung von KI-Anwendungen in der Modeindustrie.' },
      { id: 'q16o2', text: 'Fokussierung auf die Verbesserung der KI-Grafik.' },
      { id: 'q16o3', text: 'Minimierung von Risiken und Gewährleistung ethischer Standards.' },
      { id: 'q16o4', text: 'Einschränkung der KI-Forschung auf bestimmte Länder.' },
    ],
    correctAnswers: ['q16o3'],
  },
  {
    id: 'q17',
    text: 'Was ist eine Kernfunktion von DALL-E 3?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q17o1', text: 'Musikgenerierung aus Textbeschreibungen.' },
      { id: 'q17o2', text: 'Bildgenerierung.' },
      { id: 'q17o3', text: 'Automatische Transkription.' },
      { id: 'q17o4', text: 'Videobearbeitung.' },
    ],
    correctAnswers: ['q17o2'],
  },
  {
    id: 'q18',
    text: 'Welche Innovationen charakterisieren Transformer-Modelle im Vergleich zu früheren Modellen?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q18o1', text: 'Die Nutzung rekurrenter Einheiten für die sequenzielle Verarbeitung.' },
      { id: 'q18o2', text: 'Die ausschließliche Fokussierung auf statische Bildinhalte.' },
      { id: 'q18o3', text: 'Die Einführung des Aufmerksamkeitsmechanismus.' },
      { id: 'q18o4', text: 'Die Berücksichtigung der Wortposition durch Positional Encodings.' },
    ],
    correctAnswers: ['q18o3', 'q18o4'],
  },
  {
    id: 'q19',
    text: 'Für was sind Chat-Interfaces bekannt?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q19o1', text: 'Sie sind speziell für technische Nutzer konzipiert.' },
      { id: 'q19o2', text: 'Sie erfordern keine Programmierkenntnisse für die Nutzung.' },
      { id: 'q19o3', text: 'Sie ermöglichen eine einfache und direkte Interaktion mit dem Modell.' },
      { id: 'q19o4', text: 'Sie sind benutzerfreundlich und ähneln einem Messaging-Dienst.' },
    ],
    correctAnswers: ['q19o2', 'q19o3', 'q19o4'],
  },
  {
    id: 'q20',
    text: 'Was ermöglicht die Fähigkeit von Large Language Models (LLMs), natürliche Sprache zu verarbeiten?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q20o1', text: 'Sie können große Mengen an Textdaten analysieren und verstehen.' },
      { id: 'q20o2', text: 'Sie können nur einfache Texte generieren.' },
      { id: 'q20o3', text: 'Sie können nur in vordefinierten Mustern antworten.' },
      { id: 'q20o4', text: 'Sie sind auf numerische Datenanalyse beschränkt.' },
    ],
    correctAnswers: ['q20o1'],
  },
  {
    id: 'q21',
    text: 'Was ist ein Ziel der Starken KI?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q21o1', text: 'Die Entwicklung von Systemen, die nur in ihren spezifischen Anwendungsbereichen funktionieren.' },
      { id: 'q21o2', text: 'Ein echtes Verständnis der Welt und die Fähigkeit zur autonomen Lern- und Problemlösungsfähigkeit.' },
      { id: 'q21o3', text: 'Die Schaffung von Systemen mit einer umfassenden, menschenähnlichen Intelligenz.' },
      { id: 'q21o4', text: 'Begrenzung auf vorgegebene Aufgaben ohne Möglichkeit zur Anwendung auf allgemeine Probleme.' },
    ],
    correctAnswers: ['q21o2', 'q21o3'],
  },
  {
    id: 'q22',
    text: 'Welche Bereiche könnten von Bias in KI-Systemen betroffen sein?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q22o1', text: 'Personalrekrutierung.' },
      { id: 'q22o2', text: 'Wettervorhersage.' },
      { id: 'q22o3', text: 'Kreditvergabe.' },
      { id: 'q22o4', text: 'Rechtsprechung.' },
    ],
    correctAnswers: ['q22o1', 'q22o3', 'q22o4'],
  },
  {
    id: 'q23',
    text: 'Was charakterisiert generative KI im Vergleich zu diskriminativer KI?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q23o1', text: 'Sie erzeugt neue Daten, die den Trainingsdaten ähnlich sind.' },
      { id: 'q23o2', text: 'Generative Adversarial Networks (GANs) sind ein Beispiel für generative KI.' },
      { id: 'q23o3', text: 'Sie spezialisiert sich auf das Erkennen von Unterschieden zwischen Datensätzen.' },
      { id: 'q23o4', text: 'Sie wird für Klassifizierungsmodelle in Bild- oder Spracherkennungssystemen verwendet.' },
    ],
    correctAnswers: ['q23o1', 'q23o2'],
  },
  {
    id: 'q24',
    text: 'Wie nutzen KI-gestützte Tools die Technologie der natürlichsprachigen Verarbeitung (NLP)?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q24o1', text: 'Zur Komposition von Musikstücken basierend auf Liedtexten.' },
      { id: 'q24o2', text: 'Zum Verstehen und Generieren menschlicher Sprache in Chatbots.' },
      { id: 'q24o3', text: 'Zur Erzeugung von Videos basierend auf sprachlichen Anweisungen.' },
      { id: 'q24o4', text: 'Zur Analyse von Bildinhalten und Generierung von Bildbeschreibungen.' },
    ],
    correctAnswers: ['q24o2'],
  },
  {
    id: 'q25',
    text: 'Welche Technologien haben spezifische Fortschritte in der NLP (Natural Language Processing)-Technologie ermöglicht?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      { id: 'q25o1', text: 'Generative Adversarial Networks (GANs).' },
      { id: 'q25o2', text: 'Transformer.' },
      { id: 'q25o3', text: 'Deep Q Networks (DQNs).' },
      { id: 'q25o4', text: 'Long Short-Term Memory (LSTM).' },
    ],
    correctAnswers: ['q25o2', 'q25o4'],
  },
  {
    id: 'q26',
    text: 'Wie trägt KI zur Entwicklung von Robo-Advisors und personalisierten Finanzplänen bei?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q26o1', text: 'Durch die Eliminierung aller digitalen Finanzdienstleistungen.' },
      { id: 'q26o2', text: 'Durch innovative Handelsstrategien und Erstellung personalisierter Finanzpläne.' },
      { id: 'q26o3', text: 'Durch die Reduzierung der Notwendigkeit für Finanzplanung.' },
      { id: 'q26o4', text: 'Durch die Rückkehr zu traditionellen, papierbasierten Finanzsystemen.' },
    ],
    correctAnswers: ['q26o2'],
  },
  {
    id: 'q27',
    text: 'Welche Auswirkungen könnte der EU AI Act global haben?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q27o1', text: 'Er wird wahrscheinlich zu einer Verringerung der KI-Forschung weltweit führen.' },
      { id: 'q27o2', text: 'Er könnte den Import aller KI-Systeme in die EU verbieten.' },
      { id: 'q27o3', text: 'Er könnte globale Standards für KI-Regulierung setzen, ähnlich wie die DSGVO für den Datenschutz.' },
      { id: 'q27o4', text: 'Er wird speziell die Entwicklung von KI in Asien und Amerika fördern.' },
    ],
    correctAnswers: ['q27o3'],
  },
  {
    id: 'q28',
    text: 'Welches Ziel verfolgt der EU AI Act in Bezug auf generative KI-Systeme und Foundation Models?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q28o1', text: 'Die Gewährleistung von Sicherheit, Transparenz und Nichtdiskriminierung dieser Systeme.' },
      { id: 'q28o2', text: 'Die Förderung der uneingeschränkten Verbreitung von urheberrechtlich geschütztem Material.' },
      { id: 'q28o3', text: 'Die uneingeschränkte Nutzung von KI-Systemen ohne Überwachung.' },
      { id: 'q28o4', text: 'Die vollständige Automatisierung aller KI-basierten Prozesse.' },
    ],
    correctAnswers: ['q28o1'],
  },
  {
    id: 'q29',
    text: 'Für welche Aufgabe wurde das Perzeptron hauptsächlich entwickelt?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q29o1', text: 'Zeitreihenanalyse.' },
      { id: 'q29o2', text: 'Binäre Klassifikationsaufgaben.' },
      { id: 'q29o3', text: 'Bilderkennung.' },
      { id: 'q29o4', text: 'Spracherkennung.' },
    ],
    correctAnswers: ['q29o2'],
  },
  {
    id: 'q30',
    text: 'Welche Aussage beschreibt den Lernprozess im Reinforcement Learning korrekt?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { id: 'q30o1', text: 'Der Lernprozess basiert hauptsächlich auf der direkten Programmierung von Handlungsanweisungen.' },
      { id: 'q30o2', text: 'Der Agent lernt ausschließlich durch vorgegebene Beispiele und deren korrekte Antworten.' },
      { id: 'q30o3', text: 'Der Agent lernt durch einen iterativen Prozess von Aktionen, Belohnungen und Anpassungen.' },
      { id: 'q30o4', text: 'Der Agent verwendet einen festen Satz von Regeln, die sich nicht ändern.' },
    ],
    correctAnswers: ['q30o3'],
  }
];
